# Chart Releaser Configuration
owner: evilgenius-jp
git-repo: privacera-uber-chart
charts-repo: https://evilgenius-jp.github.io/privacera-uber-chart
pages-branch: main
pages-index-path: index.yaml
package-path: .cr-release-packages
release-name-template: "{{ .Name }}-{{ .Version }}"
packages-with-index: true
skip-existing: true
